# the compiler: gcc for C program, define as g++ for C++
CC = gcc

# compiler flags:
#  -g    adds debugging information to the executable file
#  -Wall turns on most, but not all, compiler warnings
CFLAGS  = -g -Wall

# libraries to include: 
#  -lm   links the math library which is not part of the standard library
LIBS = -lm

# the build target executable:
TARGET = sched

all: $(TARGET)

$(TARGET): $(TARGET).c
	$(CC) $(CFLAGS) $(LIBS) -o $(TARGET) $(TARGET).c

clean:
	$(RM) $(TARGET)
